---

- name: FIREWALLD
  become: true
  tags:
    - firewalld
  when: firewalld_active
  block:

    - name: FIREWALLD install
      community.general.pacman:
        name: firewalld
        state: present

    - name: FIREWALLD check `/etc/firewalld/zones`
      ansible.builtin.file:
        path: /etc/firewalld/zones
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: FIREWALLD template `/etc/firewalld/*.zone`
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/firewalld/zones/{{ item | basename | regex_replace('\\.j2', '') }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ lookup('fileglob', role_path + '/templates/zones/*.xml.j2', wantlist=True) }}"
      notify: FIREWALLD reload

    - name: FIREWALLD service enable/disable
      ansible.builtin.systemd_service:
        enabled: "{{ firewalld_service_enabled }}"
        name: "{{ firewalld_service_name }}"
        state: "{{ firewalld_service_state }}"
